baseURL: "https://cspaulia.github.io/cspaulia-blog/"
title: cspaulia-blog
pagination:
  pagerSize: 5
theme: PaperMod

enableEmoji: true
enableRobotsTXT: true
enableGitInfo: true
buildDrafts: false
buildFuture: false
buildExpired: false

googleAnalytics: UA-123-45

minify:
  disableXML: true
  minifyOutput: true

defaultContentLanguage: zh
defaultContentLanguageInSubdir: false
hasCJKLanguage: true

languages:
  zh:
    languageName: 中文
    languageCode: zh-CN
    weight: 1
    params:
      languageAltTitle: 中文
      label:
        text: "首页"
      # profile-mode (ZH)
      profileMode:
        enabled: true
        title: CSPaulia
        subtitle: "欢迎来到 CSPaulia 的博客。"
        description: "
          \U0001F44B 我叫 **陈帅嘉**，目前是西安交通大学人工智能与机器人研究所博士生。
          研究兴趣：暂无。"
        imageUrl: "images/ly&sj.jpg"
        imageWidth: 120
        imageHeight: 120
        imageTitle: my image
        buttons:
          - name: 出版物
            url: publications
          - name: 文章
            url: posts
          - name: 标签
            url: tags
          - name: 分类
            url: categories
          - name: 系列
            url: series

      # home-info mode (ZH)
      homeInfoParams:
        Title: "你好 \U0001F44B"
        Content: 欢迎来到 CSPaulia 的博客
    menu:
      main:
        - identifier: publications
          name: 出版物
          url: publications/
          weight: 10
        - identifier: posts
          name: 文章
          url: posts/
          weight: 20
        - identifier: series
          name: 系列
          url: series/
          weight: 30
        - identifier: categories
          name: 分类
          url: categories/
          weight: 40
        - identifier: tags
          name: 标签
          url: tags/
          weight: 50
        - identifier: archives
          name: 归档
          url: archives/
          weight: 60
        - identifier: search
          name: 搜索
          url: search/
          weight: 70
  en:
    languageName: English
    languageCode: en-US
    weight: 2
    params:
      languageAltTitle: English
      label:
        text: "Home"
      # profile-mode (EN)
      profileMode:
        enabled: true
        title: CSPaulia
        subtitle: "Welcome to CSPaulia's blog."
        description: "
          \U0001F44B My name is **Shuaijia Chen**, and I am currently a PhD student at the
          Institute of Artificial Intelligence and Robotics, Xi’an Jiaotong University.
          Research interests: None."
        imageUrl: "images/ly&sj.jpg"
        imageWidth: 120
        imageHeight: 120
        imageTitle: my image
        buttons:
          - name: Publications
            url: publications
          - name: Posts
            url: posts
          - name: Tags
            url: tags
          - name: Categories
            url: categories
          - name: Series
            url: series

      # home-info mode (EN)
      homeInfoParams:
        Title: "Hi there \U0001F44B"
        Content: Welcome to CSPaulia's blog
    menu:
      main:
        - identifier: publications
          name: Publications
          url: publications/
          weight: 10
        - identifier: posts
          name: Posts
          url: posts/
          weight: 20
        - identifier: series
          name: Series
          url: series/
          weight: 30
        - identifier: categories
          name: Categories
          url: categories/
          weight: 40
        - identifier: tags
          name: Tags
          url: tags/
          weight: 50
        - identifier: archives
          name: Archives
          url: archives/
          weight: 60
        - identifier: search
          name: Search
          url: search/
          weight: 70

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: ExampleSite
  description: "ExampleSite description"
  keywords: [Blog, Portfolio, PaperMod]
  author: CSPaulia
  GitHubUser: CSPaulia
  # author: ["Me", "You"] # multiple authors
  images: ["<link or path of image for opengraph, twitter-cards>"]
  DateFormat: "January 2, 2006"
  defaultTheme: auto # dark, light
  disableThemeToggle: false

  displayFullLangName: true # display full language name in the theme toggle

  showLastMod: true # show last modified date in single pages
  showDate: true # show date in list pages
  ShowReadingTime: true
  ShowShareButtons: true
  ShareButtons: ["twitter", "facebook", "telegram"]
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  assets:
    disableHLJS: false # to disable highlight.js
    # disableFingerprinting: true
    favicon: "<link / abs url>"
    favicon16x16: "<link / abs url>"
    favicon32x32: "<link / abs url>"
    apple_touch_icon: "<link / abs url>"
    safari_pinned_tab: "<link / abs url>"

  extend_head: |
    <link rel="stylesheet" href="{{ "css/extended/alerts.css" | absURL }}">
    <script src="{{ "js/alerts.js" | absURL }}"></script>
    <link rel="stylesheet" href="{{ "css/extended/profile.css" | absURL }}">

  syntax_highlighter: "highlight.js" # 设置代码高亮主题

  label:
    text: "Home"
    icon: /apple-touch-icon.png
    iconHeight: 35

  # profile-mode
  # profileMode/homeInfoParams are defined under languages.*.params for multilingual home.

  socialIcons:
    # - name: x
    #   url: "https://x.com/"
    # - name: stackoverflow
    #   url: "https://stackoverflow.com"
    - name: github
      url: "https://github.com/CSPaulia"
    - name: googlescholar
      url: "https://scholar.google.com/citations?user=YOUR_ID&user=FzhDpUcAAAAJ"
    - name: email
      url: "shuaijiachen@stu.xjtu.edu.cn"

  analytics:
    google:
      SiteVerificationTag: "XYZabc"
    bing:
      SiteVerificationTag: "XYZabc"
    yandex:
      SiteVerificationTag: "XYZabc"

  cover:
    hidden: false # hide everywhere but not in structured data
    hiddenInList: false # hide on list pages and home
    hiddenInSingle: true # hide on single page

  editPost:
    URL: "https://cspaulia.github.io/cspaulia-blog/content/"
    Text: "Suggest Changes" # edit text
    appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    limit: 10 # refer: https://www.fusejs.io/api/methods.html#search
    keys: ["title", "permalink", "summary", "content"]

  math: true

  busuanzi:
    enable: true

  showCopyright: true

# menu moved under languages.*.menu for multilingual support
# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
pygmentsUseClasses: true
markup:
  highlight:
    noClasses: false
    # anchorLineNos: true
    # codeFences: true
    # guessSyntax: true
    # lineNos: true
    # style: monokai
  goldmark:
    renderer:
      unsafe: true
  math:
    enable: true
  tableOfContents:
    startLevel: 2
    endLevel: 3
    ordered: false

outputs:
  home:
    - HTML
    - RSS
    - JSON # necessary for search

frontmatter:
  date:
    - date
    - publishDate
    - lastmod
  lastmod:
    - :git
    - :fileModTime
    - lastmod
    - date
    - publishDate